### PR TITLE
Added login method, wrap fetch with auto-set-cookie

### PR DESCRIPTION
**Pull request by kevin940726**
- [x] basic login method
- [x] higher-order fetch function wrapper
- [x] improve fetch wrapper code
- [x] separate each request into isolated requests

I want to make `fetch` more powerful by making it to set `cookie` and `xsrf-token` automatically. So I wrap `fetch` with a higher-order function to perform the magic. Wonder is there a better way to do this? I want to stick to `fetch` because it is a isomorphic and default-standard way. Still thinking how to make it better..., maybe next commit :)

### CODE REVIEW

**Comment by lockys** [comment]
Thanks, it's cool that you add the login functionality. it will help this module more useful.
Actually, I do not have much time to play around with JavaScript :joy: and go through the code for now.
May I add you as a collaborator(maintainer) so that you could update the code directly instead of PR?
We will find some time to go through the code and update to npm :)
Thank you.

**Comment by John-Lin** [comment]
@kevin940726 Thank you for your contributions. And we would take some time to review it.

I have an idea that keep the current version on master branch and create a new ES6 branch for this new patch. The reason why we want to retain the ES5 version is much easier for developing new applications without adding any babel plugins.

**Comment by lockys** [comment]
Also, we prefer to develop without `babel` as @John-Lin mentioned.
So could you fix the syntax which the node runtime >= 5.0 doest not support? 
If you think it is ok, I sincerely invite you to become our collaborators.
if you are willing to, please let me know.
Thank you.

**Comment by kevin940726** [comment]
Actually, writing in ES6 doesn't mean to run in ES6. If you take a look inside `package.json` you will see a `build` script which will compile the src into `lib`, which is also the main entry js of the package. So it can run in ES5 or ES6 without setting up babel for the developer using this package. All the babel dependencies are devDependencies, which are only used when we develop this package. I don't see why not developing in ES6? I suggest using ES6 will bring us nicer and cleaner code with good maintainability. If I get i all wrong that you are not talking about this :sob: ? BTW, I would be happy to become a collaborator. :smile:

**Comment by lockys** [comment]
Our main point is that develop this module without `babel`- related plugin. 
In this way, we don't need to run `npm run build` every time we update the code in `src` folder.
We can still make the ES6 version in another branch for the future usage, but in active development branch, we develop with the support of official node runtime without `babel` compiler. Some big open source module is developed in this way. Although `dcard.js` is just a small module, we can follow their development way as a practice :)
How do you think? We can discuss about this more, I add you as a collaborator! Happy collaborating!
Thank you for your nice work!

**Comment by kevin940726** [comment]
We can take the [babel-cli](https://babeljs.io/docs/usage/cli/) and use the `babel-node` command to run the babel source code directly (how I did it), so we don't have to compile it again and again while developing. Only compile the source code when publishing or testing. I agree that some big open source module is developed in ES5, but I think that it is only because they didn't have mature ES6 syntax that day. Rewriting the whole code base such big into ES6 is stupid. Also, more and more modules are developed in ES6 this day, including facebook/draft.js and redux. I think that maybe it is time to follow the new wave of evolution lol?

Yeah~ thx~~! But I agree that the ES6 module should be in the development branch rather than master. We can merge it back when the time is come. :hourglass_flowing_sand:

**Comment by lockys** [comment]
@kevin940726 
OK, I agree with your opinion :)
For this project, we could write in ES6 and compile into ES5 using `babel` when production.
@John-Lin and I have no much time to maintain this project for now.
We will go through your code when we are free.

BTW,
Could you help us maintain this project if you have time? if there is any new PRs, you could just make the decision. Thank you.
When your new patch is ready to go, please ping me. I will publish the new version to npm.
Lastly, thank you for your contributions!

**Comment by kevin940726** [comment]
Sure~ I understand.

**Comment by kevin940726** [comment]
@lockys: Can you add me to the npm owner? I would like to publish a `next` tag version of the package (or you can do it for me as well). It would not affect the current `npm install` command (as it would install the `latest` tag by default). It would be better for me to test some example code for the other project :joy:. Thanks!

**Comment by lockys** [comment]
ok! fine.

**Comment by kevin940726** [comment]
oh really ? both my npm and github account are `kevin940726`. Maybe I didn't configure something, I am so sorry :sob: . [npm](https://www.npmjs.com/~kevin940726)

**Comment by lockys** [comment]
done! please check that.

**Pull request merged**
